@startuml

start

:Iniciar sesión (Gestor);

:Crear evento;

:Ingresar datos del evento;

if (¿Datos válidos?) then (Sí)
  :Guardar evento;
  :Publicar evento;
else (No)
  :Corregir información;
endif

:Ciudadano consulta evento;

stop

@enduml