@startuml

left to right direction

actor Ciudadano
actor Administrador
actor "Gestor Comunitario" as Gestor

rectangle "Sistema de Gestión Comunitaria" {

  (Consultar eventos) as CE
  (Reservar espacio) as RE
  (Ver ubicación de eventos) as GEO
  (Calificar evento) as CAL
  (Iniciar sesión) as LOGIN
  
  (Registrar evento) as REG
  (Gestionar recursos) as GR
  (Administrar usuarios) as AU

}

' Ciudadano
Ciudadano --> CE
Ciudadano --> RE
Ciudadano --> CAL

' Gestor
Gestor --> REG
Gestor --> CE

' Administrador
Administrador --> AU
Administrador --> GR
Administrador --> CE

' Relaciones include (seguridad)
RE --> LOGIN : <<include>>
REG --> LOGIN : <<include>>
CAL --> LOGIN : <<include>>
GR --> LOGIN : <<include>>
AU --> LOGIN : <<include>>

' Relación funcional
CE --> GEO : <<include>>

@enduml